// Code generated by internal/generator; DO NOT EDIT.

package binance

import (
	"context"
	"encoding/json"
)

// DustLog returns small-balance conversion history. extra may be nil.
func (s *WalletService) DustLog(ctx context.Context, recv int64, extra map[string]string) (json.RawMessage, error) {
	p := newParams()
	for k, v := range extra {
		p.Set(k, v)
	}
	var out json.RawMessage
	if err := s.c.get(ctx, familySAPI, "/sapi/v1/asset/dribblet", p, &out, signed(), recvWindow(recv)); err != nil {
		return nil, err
	}
	return out, nil
}

// APIRestrictions returns the current API key permission set. extra may be nil.
func (s *WalletService) APIRestrictions(ctx context.Context, recv int64, extra map[string]string) (json.RawMessage, error) {
	p := newParams()
	for k, v := range extra {
		p.Set(k, v)
	}
	var out json.RawMessage
	if err := s.c.get(ctx, familySAPI, "/sapi/v1/account/apiRestrictions", p, &out, signed(), recvWindow(recv)); err != nil {
		return nil, err
	}
	return out, nil
}

// SpotDelistSchedule returns upcoming spot delistings. extra may be nil.
func (s *WalletService) SpotDelistSchedule(ctx context.Context, recv int64, extra map[string]string) (json.RawMessage, error) {
	p := newParams()
	for k, v := range extra {
		p.Set(k, v)
	}
	var out json.RawMessage
	if err := s.c.get(ctx, familySAPI, "/sapi/v1/spot/delist-schedule", p, &out, signed(), recvWindow(recv)); err != nil {
		return nil, err
	}
	return out, nil
}

// FlexiblePosition returns flexible Simple Earn positions. extra may be nil.
func (s *EarnService) FlexiblePosition(ctx context.Context, recv int64, extra map[string]string) (json.RawMessage, error) {
	p := newParams()
	for k, v := range extra {
		p.Set(k, v)
	}
	var out json.RawMessage
	if err := s.c.get(ctx, familySAPI, "/sapi/v1/simple-earn/flexible/position", p, &out, signed(), recvWindow(recv)); err != nil {
		return nil, err
	}
	return out, nil
}

// LockedPosition returns locked Simple Earn positions. extra may be nil.
func (s *EarnService) LockedPosition(ctx context.Context, recv int64, extra map[string]string) (json.RawMessage, error) {
	p := newParams()
	for k, v := range extra {
		p.Set(k, v)
	}
	var out json.RawMessage
	if err := s.c.get(ctx, familySAPI, "/sapi/v1/simple-earn/locked/position", p, &out, signed(), recvWindow(recv)); err != nil {
		return nil, err
	}
	return out, nil
}

// OrderStatus queries a convert order by quote or order id. extra may be nil.
func (s *ConvertService) OrderStatus(ctx context.Context, recv int64, extra map[string]string) (json.RawMessage, error) {
	p := newParams()
	for k, v := range extra {
		p.Set(k, v)
	}
	var out json.RawMessage
	if err := s.c.get(ctx, familySAPI, "/sapi/v1/convert/orderStatus", p, &out, signed(), recvWindow(recv)); err != nil {
		return nil, err
	}
	return out, nil
}

// APITradingStatus returns account trading-lock status. extra may be nil.
func (s *WalletService) APITradingStatus(ctx context.Context, recv int64, extra map[string]string) (json.RawMessage, error) {
	p := newParams()
	for k, v := range extra {
		p.Set(k, v)
	}
	var out json.RawMessage
	if err := s.c.get(ctx, familySAPI, "/sapi/v1/account/apiTradingStatus", p, &out, signed(), recvWindow(recv)); err != nil {
		return nil, err
	}
	return out, nil
}

// AssetDividend returns asset dividend (distribution) records. extra may be nil.
func (s *WalletService) AssetDividend(ctx context.Context, recv int64, extra map[string]string) (json.RawMessage, error) {
	p := newParams()
	for k, v := range extra {
		p.Set(k, v)
	}
	var out json.RawMessage
	if err := s.c.get(ctx, familySAPI, "/sapi/v1/asset/assetDividend", p, &out, signed(), recvWindow(recv)); err != nil {
		return nil, err
	}
	return out, nil
}

