// Command generator writes zz_generated.go from endpoints.json.
package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"strings"
	"unicode"
)

type spec struct {
	Endpoints []endpoint `json:"endpoints"`
}

type endpoint struct {
	Service string `json:"service"`
	Name    string `json:"name"`
	Method  string `json:"method"`
	Path    string `json:"path"`
	Signed  bool   `json:"signed"`
	Doc     string `json:"doc"`
}

func main() {
	root := "."
	if _, err := os.Stat("internal/generator/endpoints.json"); err != nil {
		root = "../.."
	}
	raw, err := os.ReadFile(filepath.Join(root, "internal/generator/endpoints.json"))
	if err != nil {
		fatal(err)
	}
	var s spec
	if err := json.Unmarshal(raw, &s); err != nil {
		fatal(err)
	}
	var b bytes.Buffer
	b.WriteString("// Code generated by internal/generator; DO NOT EDIT.\n\n")
	b.WriteString("package binance\n\n")
	b.WriteString("import (\n\t\"context\"\n\t\"encoding/json\"\n)\n\n")
	for _, ep := range s.Endpoints {
		recv := exportedIdent(ep.Service + "Service")
		doc := ep.Doc
		if doc == "" {
			doc = ep.Name + " calls " + ep.Path + "."
		}
		fmt.Fprintf(&b, "// %s extra may be nil.\n", doc)
		fmt.Fprintf(&b, "func (s *%s) %s(ctx context.Context, recv int64, extra map[string]string) (json.RawMessage, error) {\n", recv, ep.Name)
		b.WriteString("\tp := newParams()\n")
		b.WriteString("\tfor k, v := range extra {\n\t\tp.Set(k, v)\n\t}\n")
		b.WriteString("\tvar out json.RawMessage\n")
		opts := "weight(1)"
		if ep.Signed {
			opts = "signed(), recvWindow(recv)"
		}
		call := "get"
		switch strings.ToUpper(ep.Method) {
		case "POST":
			call = "post"
		case "DELETE":
			call = "delete_"
		case "PUT":
			call = "put"
		}
		family := "familySAPI"
		fmt.Fprintf(&b, "\tif err := s.c.%s(ctx, %s, %q, p, &out, %s); err != nil {\n", call, family, ep.Path, opts)
		b.WriteString("\t\treturn nil, err\n\t}\n\treturn out, nil\n}\n\n")
	}
	formatted, err := format.Source(b.Bytes())
	if err != nil {
		fatal(err)
	}
	out := filepath.Join(root, "zz_generated.go")
	if err := os.WriteFile(out, formatted, 0o644); err != nil {
		fatal(err)
	}
}

func exportedIdent(s string) string {
	if s == "" {
		return s
	}
	r := []rune(s)
	r[0] = unicode.ToUpper(r[0])
	return string(r)
}

func fatal(err error) {
	fmt.Fprintln(os.Stderr, err)
	os.Exit(1)
}
